### ISSUE TITLE
[iOS] Social Login and Authentication

### ISSUE THREAD

**Issue by marcotuts** [openedx/openedx-app-ios#103]
### Goal
This project involves adding social authentication options including - Apple, Microsoft, Facebook, and Google to the base open edx application 

![Image](https://github.com/openedx/openedx-app-ios/assets/121940663/e803f19c-13ed-4922-894d-34b8f0feef52)

**Slack:** #wg-product-mobile
**Requirement Definition:** [Confluence Project Page](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3891134465/Project+-+Social+Authentication)

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-ios/issues/113
- [ ] https://github.com/openedx/openedx-app-ios/issues/114
- [ ] Confluence Project Page ready for review
- [ ] https://github.com/openedx/openedx-app-ios/issues/159
```

**Comment by Kelketek** [comment]
Calling attention to https://github.com/openedx/openedx-app-ios/pull/65#issuecomment-1832657613 , which is at least a partial solution to this problem, and which if provided additional resources could be completed.
