### ISSUE TITLE
Persistent Mobile Notifications / Inbox

### ISSUE THREAD

**Issue by marcotuts** [openedx/openedx-app-ios#107]
### Goal
Supporting improved course navigation for mobile learners to support sequence based learning progressions in courses, and top level navigation cleanup as well.

**Slack:** #wg-product-mobile
**Requirement Definition:** [Confluence Project Page](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3781754886/Project+-+Mobile+Notifications+Discovery+FC-25b)

```[tasklist]
### Tasks
- [ ] Product Requirement Discovery
- [ ] Design Discovery / Early Definition
- [ ] Confluence Project Page ready for review
```

**Comment by marcotuts** [comment]
The Raccoon Gang team has started early technical review, and the Schema team is planning tentatively to pick up some early product / design discovery for this but this is not finalized!

**Comment by marcotuts** [comment]
Product design / definition is completed and reflected in the confluence page.

**Comment by edschema** [comment]
Closing this issue and moving the epic to the new wg-mobile repo
