### ISSUE TITLE
Improved Program Experience

### ISSUE THREAD

**Issue by marcotuts** [openedx/openedx-app-ios#108]
### Goal
Improvements to the program experience (considering both native and webview expressions) on mobile application.

**Slack:** #wg-product-mobile
**Requirement Definition:** Not Drafted

```[tasklist]
### Tasks
- [ ] Product Requirement Discovery
- [ ] Design Discovery / Early Definition
- [ ] Confluence Project Page ready for review
- [ ] Development scope / sizing
```

**Comment by marcotuts** [comment]
This is also another project that may be helpful to have edX drive next steps for since programs are currently something they make heavy use of via the discovery service. How we might support program definition and thus mobile app expression for non-discovery service users is still TBD!
