### ISSUE TITLE
[iOS] Improved Navigation - Dashboard Level (FC-47)

### ISSUE THREAD

**Issue by marcotuts** [openedx/openedx-app-ios#110]
### Goal
Supporting improved course navigation for mobile learners to support sequence based learning progressions in courses, and top level navigation cleanup as well.

**Slack:** #wg-product-mobile
**Requirement Definition:** [Confluence Project Page](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3781754910/Project+-+Course+Navigation+Improvements+FC-28b)

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-ios/issues/180
- [ ] https://github.com/openedx/openedx-app-ios/issues/320
- [ ] https://github.com/openedx/openedx-app-ios/issues/321
- [x] Cards: Primary Cards
- [x] Cards: Basic Cards
- [x] Cards: Progress Cards
- [x] View: (All) My Courses View
- [x] Case: No Enrolled Courses Message
```

**Comment by touchapp** [comment]
Hi @marcotuts are there any updates on this? Due to the approaching deadline we may remove this from scope for MVP.

**Comment by marcotuts** [comment]
I don't think any of the planned work here impacts P0 level edX gaps, most of the work we are proposing at the My Courses level would be an improvement, so not somethign that needs to be MVP (for edX) scoped.

**Comment by marcotuts** [comment]
@volodymyr-chekyrta  would you mind helping with the status of these tasks / items, I think this was part of us trying to surface more in progress detail work via epics, but we should mark these closed / done accordingly and regroup on what if any additional detail we should provide within epics in future quarters.

**Comment by volodymyr-chekyrta** [comment]
> @volodymyr-chekyrta would you mind helping with the status of these tasks / items, I think this was part of us trying to surface more in progress detail work via epics, but we should mark these closed / done accordingly and regroup on what if any additional detail we should provide within epics in future quarters.

Yes, let's review them 🙌
I think some of them are being developed by the Axinite team right now; let's review the whole epic at the next meeting and provide updates
