### ISSUE TITLE
[iOS] Improved Navigation - Course Home Level

### ISSUE THREAD

**Issue by marcotuts** [openedx/openedx-app-ios#111]
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-ios/issues/121
- [ ] https://github.com/openedx/openedx-app-ios/issues/154
- [ ] https://github.com/openedx/openedx-app-ios/issues/155
- [ ] https://github.com/openedx/openedx-app-ios/issues/199
```

**Comment by marcotuts** [comment]
Reopening this epic - this work is not complete, but was used to track some edX MVP tickets / tasks previously.
