### ISSUE TITLE
[iOS] Improved Navigation - Sequences Level

### ISSUE THREAD

**Issue by marcotuts** [openedx/openedx-app-ios#112]
**Goal:**
Improved navigation for Open edX mobile to echo desktop / Studio unit page composition, along with opportunistic performance updates to how we render these views. 

We are actively working on product / design definition for this, but plan to introduce expanded visual progress for unit pages on mobile, and putting the next button at the bottom of the page scroll for units. Some blocks, like videos will need updates to let you have an initial smaller Transcript area that can be expanded, allowing learners to scroll past videos to see any blocks after in the unit page easily. 

**Confluence Documentation** - https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3781754910/Project+-+Streamlined+Course+Navigation+Sequences+FC-0046

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-ios/issues/156
- [ ] https://github.com/openedx/openedx-app-ios/issues/200
- [ ] https://github.com/openedx/openedx-app-ios/pull/190
```

**Comment by edschema** [comment]
Closing this issue and moving the epic to the new wg-mobile repo
