### ISSUE TITLE
[iOS] Account Settings Cleanup - Support / FAQ / Email (2U)

### ISSUE THREAD

**Issue by touchapp** [openedx/openedx-app-ios#117]
**Goal**

This project involves adding dedicated support page, FAQ, Email and viewing Terms of Service / Privacy Policies inside application  

Slack: #wg-product-mobile

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-ios/issues/118
- [ ] https://github.com/openedx/openedx-app-ios/issues/119
- [ ] https://github.com/openedx/openedx-app-ios/issues/120
- [ ] https://github.com/openedx/openedx-app-ios/issues/203
```

**Comment by marcotuts** [comment]
This effort would benefit from some UX definition and clarity - we definitely need to have the account settings page be more flexible and include out of the box additional configurable links / references for student support and help.

**Comment by rnr** [comment]
@moiz994 could we specify which exactly fields/areas should we have in this View?
Should we follow current edX app? All these fields are required fr openEdX too or we need hide something with Feature Flags?
Like some list or something like this. 
Thank you
cc @k1rill

**Comment by moiz994** [comment]
Hey Anton, good question. We should be following the prod edX app for our case but for open edX the following are not required:

- Cookie Policy
- Do Not Sell my Personal Information
- Delete my Account

Please see the below screenshot of the current prod app profile screen for context:

<img src="https://github.com/openedx/openedx-app-ios/assets/109789173/81346df3-39ce-4f1f-8389-2b661993b04f" width="400">

Also, quick question, are we currently just implementing the design for the screen or also looking into the functionality of the buttons on this screen?


@marcotuts I think we need to align here as well on the design and scope of the profile tab.

**Comment by k1rill** [comment]
![IMAGE 2023-12-12 15:36:43](https://github.com/openedx/openedx-app-ios/assets/1063094/18a929c2-d534-42b1-abb6-7cfb12698386)
Delete account is now inside Edit Account screen in the open edX app

**Comment by moiz994** [comment]
oh, yes! Thanks for sharing this. I think there was some compliance issue that needed us to bring it out in the front for some reason but I can not recall exactly. I think product teams need to sync up on this. Let's keep it as it is for now. We can create separate tickets for compliance considerations later.

**Comment by moiz994** [comment]
@k1rill can you share a video or screenshot of what the current implementation is that awaiting PR approval?
