### ISSUE TITLE
[iOS] Theming Customization Improvements

### ISSUE THREAD

**Issue by marcotuts** [openedx/openedx-app-ios#153]
### Goal
Simplify the theme configuration for builds of the new openedx mobile app 

**Slack:** #wg-product-mobile
**Requirement Definition:** Not Drafted

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-ios/pull/182
- [ ] https://github.com/openedx/openedx-app-ios/issues/223
- [ ] https://github.com/openedx/openedx-app-ios/issues/237
- [ ] https://github.com/openedx/openedx-app-ios/issues/238
- [ ] https://github.com/openedx/openedx-app-ios/pull/311
- [ ] https://github.com/openedx/openedx-app-ios/pull/307
- [ ] https://github.com/openedx/openedx-app-ios/pull/294
```

**Comment by marcotuts** [comment]
Should look into configurable text (title / subtitles / etc)

**Comment by moiz994** [comment]
@saeedbashir is there any work left for theme on iOS?
