### ISSUE TITLE
[iOS] Q4 2023 - Misc Bugs / Cleanup Tasks

### ISSUE THREAD

**Issue by marcotuts** [openedx/openedx-app-ios#157]
Goal: 

This is a way to organize misc bugs and cleanup tasks that have otherwise no epic / home to associate them with and thus aren't represented on the roadmap. 

For now we will try a quarterly ticket for iOS / Android to group these as an epic label. 

(FYI @moiz994 and @HamzaIsrar12 based on a recent ticket conversation)
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-ios/issues/186
- [ ] https://github.com/openedx/openedx-app-ios/issues/187
- [ ] https://github.com/openedx/openedx-app-ios/issues/201
- [ ] https://github.com/openedx/openedx-app-ios/issues/208
- [ ] https://github.com/openedx/openedx-app-ios/issues/205
- [ ] https://github.com/openedx/openedx-app-ios/issues/204
- [ ] https://github.com/openedx/openedx-app-ios/issues/211
```
