### ISSUE TITLE
[iOS] iPad Support Improvements

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-ios#170]
Epic ticket for problems, etc. for iPad
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-ios/issues/234
- [ ] https://github.com/openedx/openedx-app-ios/issues/304
- [ ] https://github.com/openedx/openedx-app-ios/issues/308
```
