### ISSUE TITLE
Experience Gaps

### ISSUE THREAD

**Issue by miankhalid** [openedx/openedx-app-ios#222]
```[tasklist]
### Tasks
- [ ] Implement course not started experience
- [ ] Implement course access expired course
- [ ] Errors handling on course home/dashboard screen
- [ ] Changes to the new Course info Blocks API to include course data with the course blocks
- [ ] Handle the case where a user changes their primary email address from Accounts page on website
```

**Comment by marcotuts** [comment]
Would it be possible to add a bit more detail on the use case / additions here? 

This might also be a good candidate for having items added to the Bugs / Issues Epic (we can create one for 2024 Q1/Q2 and close our Q4 one soon.

**Comment by miankhalid** [comment]
Currently blocked due to this PR https://github.com/openedx/edx-platform/pull/34273# that would update the Blocks API to do what's needed to consider the course dashboard feature complete.

**Comment by marcotuts** [comment]
It may be helpful to shift these to be tasks within Course Home Navigation updates or another related epic, or the Q1 / Q2 Misc Gaps / Fixes ticket. Can discuss in next check-in?

**Comment by miankhalid** [comment]
yep, makes sense! lets discuss in the next checkin.

**Comment by marcotuts** [comment]
I'm going to mark this epic closed @miankhalid  - Lets add whatever needs to be recreated as tasks within the Q3 cleanup tasks epic as a next step, can chat about it post MVP launch as I don't think these impact that release for you.
