### ISSUE TITLE
[iOS] Expanded xBlocks Support

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-ios#236]
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-ios/issues/174
- [ ] https://github.com/openedx/openedx-app-ios/issues/178
- [ ] https://github.com/openedx/openedx-app-ios/issues/175
- [ ] https://github.com/openedx/openedx-app-ios/issues/179
```
