### ISSUE TITLE
[iOS] Offline - Video Downloads

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-ios#242]
**Goal**
The ability to access a full course experience on your phone even without connectivity will enable learning on the go and in limited bandwidth environments.
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-ios/issues/167
- [ ] https://github.com/openedx/openedx-app-ios/issues/166
- [ ] https://github.com/openedx/openedx-app-ios/issues/168
- [ ] https://github.com/openedx/openedx-app-ios/issues/217
- [ ] https://github.com/openedx/openedx-app-ios/issues/228
- [ ] https://github.com/openedx/openedx-app-ios/issues/229
- [ ] https://github.com/openedx/openedx-app-ios/issues/255
- [ ] https://github.com/openedx/openedx-app-ios/issues/251
```

**Comment by marcotuts** [comment]
We should connect on this prior to starting development - wanted to make sure this was clear early on - (thanks for creating these tickets!) 

FYI @nizmaylova , @touchapp

**Comment by marcotuts** [comment]
This seems like it is close to done / done, checking in on this - updated status to be in acceptance / review
