### ISSUE TITLE
[iOS] Q2 2024 - Misc Bugs / Cleanup Tasks

### ISSUE THREAD

**Issue by marcotuts** [openedx/openedx-app-ios#394]
Quarterly ticket (for Q2 2024) to group iOS tickets as an epic label.
This is a way to organize misc bugs and cleanup tasks that have otherwise no epic / home to associate them with and thus aren't represented on the roadmap.
```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-ios/issues/361
- [ ] https://github.com/openedx/openedx-app-ios/issues/390
- [ ] https://github.com/openedx/openedx-app-ios/issues/391
- [ ] https://github.com/openedx/openedx-app-ios/issues/383
- [ ] https://github.com/openedx/openedx-app-ios/issues/358
- [ ] https://github.com/openedx/openedx-app-ios/issues/355
- [ ] https://github.com/openedx/openedx-app-ios/issues/304
- [ ] https://github.com/openedx/openedx-app-ios/issues/285
- [ ] https://github.com/openedx/openedx-app-ios/issues/255
- [ ] https://github.com/openedx/openedx-app-ios/issues/449
```

**Comment by marcotuts** [comment]
Linked all open bugs to Q3, kept the Q2 link intact so it is easier to see when we originally linked / filed a ticket.
