### ISSUE TITLE
[iOS] Quick Win Feature Gaps (FC-0028)

### ISSUE THREAD

**Issue by marcotuts** [openedx/openedx-app-ios#84]
### Goal
The following project is a collection of several different items identified by the feature gap exercises completed by the mobile working group and edX mobile teams. Upon completion approximately 34% of the [gaps identified ](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3836837895)that have the smallest development scope and are quickest to complete should be delivered.

**Slack:** #wg-product-mobile
**Requirement Definition:** [Confluence Project Page](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3851780097/Project+-+Quick+Win+Feature+Gap+List)

```[tasklist]
### Tasks
- [x] Gap List Merge - edx and mobile working group
- [ ] https://github.com/openedx/openedx-app-ios/issues/88
- [ ] https://github.com/openedx/openedx-app-ios/issues/89
- [ ] https://github.com/openedx/openedx-app-ios/issues/90
- [ ] https://github.com/openedx/openedx-app-ios/issues/91
- [ ] https://github.com/openedx/openedx-app-ios/issues/92
- [ ] https://github.com/openedx/openedx-app-ios/issues/93
- [ ] https://github.com/openedx/openedx-app-ios/issues/94
- [ ] https://github.com/openedx/openedx-app-ios/issues/95
- [ ] https://github.com/openedx/openedx-app-ios/issues/96
- [ ] https://github.com/openedx/openedx-app-ios/issues/97
```

**Comment by marcotuts** [comment]
Marking this closed / done.
