### ISSUE TITLE
[iOS] Improved Navigation - App Level (FC-47)

### ISSUE THREAD

**Issue by marcotuts** [openedx/openedx-app-ios#87]
### Goal
Supporting improved course navigation for mobile learners to support sequence based learning progressions in courses, and top level navigation cleanup as well.

**Slack:** #wg-product-mobile
**Requirement Definition:** [Confluence Project Page](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3781754910/Project+-+Course+Navigation+Improvements+FC-28b)

```[tasklist]
### Tasks
- [x] Product Requirement Discovery
- [x] Design Discovery / Early Definition
- [x] Confluence Project Page ready for review
- [ ] https://github.com/openedx/openedx-app-ios/issues/318
- [ ] https://github.com/openedx/openedx-app-ios/issues/319
```

**Comment by marcotuts** [comment]
This project will be further split into 4 areas, one focused on App Level Navigation, one focused on My Courses Dashboard, Courses Home, and finally Sequence Navigation. For now all issues will link to the same product confluence documentation.
